# Generated by Django 5.2.5 on 2025-08-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender_alter_user_user_type_employerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
