# Generated by Django 5.2.5 on 2025-08-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=30)),
                ('job_type', models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time'), ('O', 'Other')], max_length=1)),
                ('job_pay_type', models.CharField(choices=[('S', 'Salary'), ('H', 'Hourly'), ('O', 'Other')], max_length=1)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(max_length=50)),
                ('email_to', models.EmailField(max_length=254)),
                ('url_to', models.URLField()),
            ],
        ),
    ]
